### ISSUE TITLE
"Zero width for layer" - Exception

### ISSUE THREAD

**Issue by matheusjkweber** [ashfurrow/Nimble-Snapshots#152]
I am trying to record a snapshot of the UIViewController`s view and I am getting this error:

> unexpected exception raised: Zero width for layer <CALayer: 0x60000042b2c0>

What does that mean?

**Comment by ashfurrow** [comment]
Typically this happens when you try to take a snapshot of a view without a size. Are any of the subviews within the view controller relying on screen constraints that might not be present in the unit test? You can try doing stuff like this, too:

https://github.com/artsy/eidolon/blob/1523618a663ac783838638ff44b62ee60b5424e3/Kiosk/App/UIViewControllerExtensions.swift#L7-L10

That project has a bunch of snapshot tests, which might be helpful as examples.

This error you're seeing is bubbling up from [iOSSnapshotTestCase](https://github.com/uber/ios-snapshot-test-case) so if you keep running into this, I'd open up an issue with them to get further troubleshooting help. Good luck!
