### ISSUE TITLE
How to correctly take a snapshot of a view with custom CALayer?

### ISSUE THREAD

**Issue by CharlotteErpels19931** [ashfurrow/Nimble-Snapshots#191]
I wrote a view with a custom CALayer, but the snapshot looks entirely different from when I see the view on a simulator or device. If you need more info, let me know. How can I capture the custom view with the custom CALayer in a correct way?

**Comment by ashfurrow** [comment]
Sounds like an issue with [the underlying snapshot library](https://github.com/uber/ios-snapshot-test-case). I would verify that the bug happens when using that library directly, and then open an issue there with your test case. You should also look through their existing issues to see if someone else has a similar problem, maybe they found a workaround solution already.

**Comment by CharlotteErpels19931** [comment]
Found the issue a couple weeks ago. When calling `recordSnapshot` or `snapshot`, you need to specify that it uses draw rect, like this  `recordSnapshot(usesDrawRect: true)` and `snapshot(usesDrawRect: true)`. Then it works like a charm.
