### ISSUE TITLE
Xcode 15 support and Nimble dependency

### ISSUE THREAD

**Issue by BisuGit** [ashfurrow/Nimble-Snapshots#278]
Looks like for xcode 15 to work properly it requires Nimble version 13.0.0+ which contains this [fix](https://github.com/Quick/Nimble/pull/1090) however nimble snapshots has a specific nimble dependency what is lower than 13.0.0 . 

A fix to this issue would be to update nimble snapshot's Nimble dependency to 13.0.0+

**Comment by ashfurrow** [comment]
Wasn’t this solved with #268?

**Comment by ashfurrow** [comment]
Ah you’re right. I see the issue here:

https://github.com/ashfurrow/Nimble-Snapshots/blob/935a4e49d28e4387626dd807529ff0170553e69f/Nimble-Snapshots.podspec#L28

We can update that to 13 to fix the bug. I suppose that _might_ exclude Xcode 14 users from using the latest version of Nimble/Nimble-Snapshots, but I don’t think that’s a huge issue. 

Do you have time to open a pull request?

**Comment by BisuGit** [comment]
Sorry I do not have time to open a pull request. It looks like it may take some effort to update? https://github.com/ashfurrow/Nimble-Snapshots/pull/275
I was just hoping to flag this issue.

**Comment by ashfurrow** [comment]
@eddie-esc did you push it to your fork?

**Comment by ddanielczyk** [comment]
@ashfurrow  I created PR for that, wanna take a look? Thanks! https://github.com/ashfurrow/Nimble-Snapshots/pull/279
